//! YouTube authentication for yt-dlp.
//!
//! Cookies are the only mechanism available: yt-dlp's OAuth login no longer
//! works with YouTube and password login was removed, so every path here ends
//! in a Netscape `cookies.txt` passed as `--cookies`, or in
//! `--cookies-from-browser` reading an installed browser's jar directly.
//!
//! Authentication is only needed for content that requires an account —
//! age-restricted, members-only and private videos. It is deliberately off by
//! default: using an account with yt-dlp risks YouTube restricting it.

use std::fs;
use std::path::{Path, PathBuf};

use tauri::{AppHandle, Manager, Url, WebviewUrl, WebviewWindow, WebviewWindowBuilder};

use crate::models::{AuthStatus, Settings};
use crate::store::{self, SettingsState};

pub const LOGIN_WINDOW_LABEL: &str = "youtube-login";

const LOGIN_URL: &str = "https://accounts.google.com/ServiceLogin?service=youtube";

/// Domains whose cookies YouTube needs to see. Sign-in happens on
/// accounts.google.com but the session cookies land on `.google.com`.
const COOKIE_DOMAINS: [&str; 2] = ["https://www.youtube.com", "https://accounts.google.com"];

/// Cookie names that only exist on a signed-in Google session.
const SESSION_COOKIES: [&str; 4] = ["SID", "SAPISID", "__Secure-3PSID", "__Secure-1PSID"];

/// Browsers `--cookies-from-browser` understands.
pub const SUPPORTED_BROWSERS: [&str; 9] = [
    "brave", "chrome", "chromium", "edge", "firefox", "opera", "safari", "vivaldi", "whale",
];

fn cookies_path(app: &AppHandle) -> Result<PathBuf, String> {
    let dir = app
        .path()
        .app_config_dir()
        .map_err(|e| format!("cannot resolve app config dir: {e}"))?;
    fs::create_dir_all(&dir).map_err(|e| format!("cannot create config dir: {e}"))?;
    Ok(dir.join("cookies.txt"))
}

/// yt-dlp arguments that authenticate a request, or empty when authentication
/// is off. Shared by analyze, download and watch so signing in once applies
/// everywhere.
pub fn args_for(app: &AppHandle, settings: &Settings) -> Vec<String> {
    match settings.auth_mode.as_str() {
        "file" => match cookies_path(app) {
            Ok(path) if path.exists() => {
                vec!["--cookies".into(), path.to_string_lossy().into_owned()]
            }
            _ => Vec::new(),
        },
        "browser" => match settings.cookies_browser.as_deref() {
            Some(browser) if SUPPORTED_BROWSERS.contains(&browser) => {
                vec!["--cookies-from-browser".into(), browser.to_string()]
            }
            _ => Vec::new(),
        },
        _ => Vec::new(),
    }
}

/// Convenience wrapper that reads the current settings itself.
pub fn args(app: &AppHandle) -> Vec<String> {
    let settings = {
        let state = app.state::<SettingsState>();
        let guard = state.0.lock().unwrap();
        guard.clone()
    };
    args_for(app, &settings)
}

// ---------- Netscape cookie file ----------

/// Serialises cookies into the Netscape format yt-dlp expects.
///
/// The `#HttpOnly_` domain prefix is how that format carries the HttpOnly flag;
/// yt-dlp understands it, and YouTube's session cookies are HttpOnly, so
/// dropping it would discard exactly the cookies that matter.
fn to_netscape(cookies: &[(String, CookieFields)]) -> String {
    let mut out = String::from("# Netscape HTTP Cookie File\n");
    out.push_str("# Generated by FreeTubium. Do not share this file.\n\n");
    for (_, c) in cookies {
        let prefix = if c.http_only { "#HttpOnly_" } else { "" };
        let include_subdomains = if c.domain.starts_with('.') {
            "TRUE"
        } else {
            "FALSE"
        };
        let secure = if c.secure { "TRUE" } else { "FALSE" };
        out.push_str(&format!(
            "{}{}\t{}\t{}\t{}\t{}\t{}\t{}\n",
            prefix,
            c.domain,
            include_subdomains,
            c.path,
            secure,
            // 0 marks a session cookie in this format.
            c.expires.unwrap_or(0),
            c.name,
            c.value,
        ));
    }
    out
}

struct CookieFields {
    domain: String,
    path: String,
    secure: bool,
    http_only: bool,
    expires: Option<u64>,
    name: String,
    value: String,
}

/// Reads the cookie jar of a webview for the domains YouTube cares about.
fn collect_cookies(window: &WebviewWindow) -> Result<Vec<(String, CookieFields)>, String> {
    let mut collected: Vec<(String, CookieFields)> = Vec::new();

    for domain in COOKIE_DOMAINS {
        let url = Url::parse(domain).map_err(|e| format!("bad cookie domain {domain}: {e}"))?;
        let cookies = window
            .cookies_for_url(url)
            .map_err(|e| format!("cannot read cookies for {domain}: {e}"))?;

        for cookie in cookies {
            let name = cookie.name().to_string();
            let host = domain.trim_start_matches("https://").to_string();
            let cookie_domain = cookie.domain().map(str::to_string).unwrap_or(host);
            // Same cookie can be reported for several URLs; key on the tuple
            // that makes it unique in the cookie file.
            let key = format!("{cookie_domain}|{name}");
            if collected.iter().any(|(k, _)| *k == key) {
                continue;
            }
            collected.push((
                key,
                CookieFields {
                    domain: cookie_domain,
                    path: cookie.path().unwrap_or("/").to_string(),
                    secure: cookie.secure().unwrap_or(false),
                    http_only: cookie.http_only().unwrap_or(false),
                    expires: cookie
                        .expires_datetime()
                        .map(|t| t.unix_timestamp().max(0) as u64),
                    name,
                    value: cookie.value().to_string(),
                },
            ));
        }
    }

    Ok(collected)
}

/// Parses a Netscape cookie file well enough to report status and to reject
/// files that are not cookie files at all.
fn inspect_cookie_file(path: &Path) -> (usize, bool, Option<u64>) {
    let Ok(text) = fs::read_to_string(path) else {
        return (0, false, None);
    };

    let mut count = 0usize;
    let mut signed_in = false;
    let mut earliest: Option<u64> = None;

    for line in text.lines() {
        // `#HttpOnly_` lines are real cookies; other comments are not.
        let line = line.strip_prefix("#HttpOnly_").unwrap_or(line);
        if line.starts_with('#') || line.trim().is_empty() {
            continue;
        }
        let fields: Vec<&str> = line.split('\t').collect();
        if fields.len() < 7 {
            continue;
        }
        count += 1;
        let name = fields[5];
        if SESSION_COOKIES.contains(&name) {
            signed_in = true;
            if let Ok(expires) = fields[4].parse::<u64>() {
                if expires > 0 && earliest.is_none_or(|current| expires < current) {
                    earliest = Some(expires);
                }
            }
        }
    }

    (count, signed_in, earliest)
}

fn status_for(app: &AppHandle, settings: &Settings) -> AuthStatus {
    let path = cookies_path(app).ok();
    let exists = path.as_ref().is_some_and(|p| p.exists());
    let (cookie_count, signed_in, expires_at) = match path.as_ref().filter(|p| p.exists()) {
        Some(p) => inspect_cookie_file(p),
        None => (0, false, None),
    };

    AuthStatus {
        mode: settings.auth_mode.clone(),
        browser: settings.cookies_browser.clone(),
        cookie_file_exists: exists,
        cookie_count,
        signed_in,
        expires_at,
    }
}

/// Persists an auth-related settings change and returns the fresh status.
fn update_settings(
    app: &AppHandle,
    mutate: impl FnOnce(&mut Settings),
) -> Result<AuthStatus, String> {
    let settings = {
        let state = app.state::<SettingsState>();
        let mut guard = state.0.lock().unwrap();
        mutate(&mut guard);
        guard.clone()
    };
    store::save_settings(app, &settings)?;
    Ok(status_for(app, &settings))
}

// ---------- commands ----------

/// Current authentication status.
#[tauri::command]
pub fn youtube_auth_status(app: AppHandle) -> AuthStatus {
    let settings = {
        let state = app.state::<SettingsState>();
        let guard = state.0.lock().unwrap();
        guard.clone()
    };
    status_for(&app, &settings)
}

/// Opens a window on Google's sign-in page. Cookies are captured separately so
/// the user stays in control of when the session is stored.
#[tauri::command]
pub fn open_youtube_login(app: AppHandle) -> Result<(), String> {
    if let Some(existing) = app.get_webview_window(LOGIN_WINDOW_LABEL) {
        let _ = existing.show();
        let _ = existing.set_focus();
        return Ok(());
    }

    let url = Url::parse(LOGIN_URL).map_err(|e| format!("bad login URL: {e}"))?;
    WebviewWindowBuilder::new(&app, LOGIN_WINDOW_LABEL, WebviewUrl::External(url))
        .title("Sign in to YouTube")
        .inner_size(520.0, 720.0)
        .min_inner_size(400.0, 560.0)
        .build()
        .map_err(|e| format!("cannot open the sign-in window: {e}"))?;
    Ok(())
}

/// Reads the sign-in window's cookies into `cookies.txt` and switches
/// authentication on.
///
/// Must stay `async` and do the read off the main thread: `cookies_for_url`
/// deadlocks on Windows when called from a synchronous command.
#[tauri::command]
pub async fn capture_youtube_cookies(app: AppHandle) -> Result<AuthStatus, String> {
    // Prefer the sign-in window, but fall back to the main window so cookies
    // picked up by the embedded player also work.
    let window = app
        .get_webview_window(LOGIN_WINDOW_LABEL)
        .or_else(|| app.get_webview_window("main"))
        .ok_or_else(|| "no window available to read cookies from".to_string())?;

    let cookies = tauri::async_runtime::spawn_blocking(move || collect_cookies(&window))
        .await
        .map_err(|e| format!("cookie read failed: {e}"))??;

    if cookies.is_empty() {
        return Err("No YouTube cookies found. Sign in first, then capture.".into());
    }

    let path = cookies_path(&app)?;
    fs::write(&path, to_netscape(&cookies))
        .map_err(|e| format!("cannot write the cookie file: {e}"))?;

    let (_, signed_in, _) = inspect_cookie_file(&path);
    if !signed_in {
        // Guest cookies are not useful and would silently fail later.
        let _ = fs::remove_file(&path);
        return Err(
            "Those cookies are not signed in. Complete the sign-in, then capture again.".into(),
        );
    }

    if let Some(window) = app.get_webview_window(LOGIN_WINDOW_LABEL) {
        // Closing the session reduces the chance YouTube rotates these cookies
        // out from under us.
        let _ = window.close();
    }

    update_settings(&app, |settings| {
        settings.auth_mode = "file".into();
    })
}

/// Imports a `cookies.txt` the user exported themselves.
#[tauri::command]
pub fn import_cookies_file(app: AppHandle, path: String) -> Result<AuthStatus, String> {
    let source = PathBuf::from(&path);
    if !source.is_file() {
        return Err(format!("{path} is not a file"));
    }

    let (count, _, _) = inspect_cookie_file(&source);
    if count == 0 {
        return Err(
            "That file has no cookies in Netscape format. Export it with a cookies.txt browser extension.".into(),
        );
    }

    let target = cookies_path(&app)?;
    fs::copy(&source, &target).map_err(|e| format!("cannot copy the cookie file: {e}"))?;

    update_settings(&app, |settings| {
        settings.auth_mode = "file".into();
    })
}

/// Switches to reading cookies straight from an installed browser.
#[tauri::command]
pub fn use_browser_cookies(app: AppHandle, browser: String) -> Result<AuthStatus, String> {
    if !SUPPORTED_BROWSERS.contains(&browser.as_str()) {
        return Err(format!("unsupported browser: {browser}"));
    }
    update_settings(&app, |settings| {
        settings.auth_mode = "browser".into();
        settings.cookies_browser = Some(browser);
    })
}

/// Turns authentication off and deletes the stored cookies.
#[tauri::command]
pub fn clear_youtube_auth(app: AppHandle) -> Result<AuthStatus, String> {
    if let Ok(path) = cookies_path(&app) {
        let _ = fs::remove_file(path);
    }
    update_settings(&app, |settings| {
        settings.auth_mode = "none".into();
        settings.cookies_browser = None;
    })
}
